name: CI
env:
  RUBY_VERSION: 3.4.1
  ASAAS_API_KEY: "Secret"

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install gems
        run: bundle install

      - name: Check code
        run: rubocop
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install gems
        run: bundle install

      - name: Setup rails dependencies
        working-directory: ./spec/dummy
        run: bundle install

      - name: Setup database
        working-directory: ./spec/dummy
        run: bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rspec
